### PR TITLE
possible fix for #11

### PR DESCRIPTION
**Pull request by maphew**
turns out there is an idnum specifically for "Start Menu\Programs" folder

### CODE REVIEW

**Comment by maphew** [comment]
I also researched CSIDL approaches and found a mature module by ActiveState called **appdirs**. https://github.com/ActiveState/appdirs/blob/master/appdirs.py. It uses 3 access methods in cascade, attempting each in order: pywin32, ctypes, registry.

Their ctypes method does not use Eryk Sun's newer approach with GUID instead of CLSID. Also note the special handling of unicode in path name (without handling the path is not returned at all). I think Eryk's is the better one, simpler overall, though I don't like how it loads all IDs into the main namespace. Makes things very noisy. I'm going to try wrap it in named tuple. No idea how long that might take (or even if I can!) so this fix is probably best to go with for now.

**Comment by maphew** [comment]
forgot to say: this fix works for cmdline on my win10 surface tablet.

**Comment by newville** [comment]
@maphew That looks OK to me. I'll merge and we can test it.

I sort of like the CSIDL named constants more than just a literal number, as it looks less magic and (mostly) indicates the intention.

So, is `win32com.shell.shellcon.CSIDL_PROGRAMS == 2`  or does it point to the actual folder? 

I'm not at a Windows machine at the moment, but that looks like the suggested approach from https://docs.microsoft.com/en-us/windows/win32/shell/csidl

That also suggests that HOME should be taken from CSIDL_PROFILE and that DESKTOP should be taken from CSIDL_DESKTOP.

**Comment by newville** [comment]
@maphew as a follow up, I get this:

    >>> from win32com.shell  import shell, shellcon

    >>>  shell.SHGetFolderPath(0, shellcon.CSIDL_PROFILE, None, 0)
    'C:\\Users\\username'

    >>> shell.SHGetFolderPath(0, shellcon.CSIDL_PROGRAMS, None, 0)
    'C:\\Users\\username\\AppData\\Roaming\\Microsoft\\Windows\\Start Menu\\Programs'

    >>> shell.SHGetFolderPath(0, shellcon.CSIDL_COMMON_PROGRAMS, None, 0)
    'C:\\ProgramData\\Microsoft\\Windows\\Start Menu\\Programs'

    >>> shell.SHGetFolderPath(0, shellcon.CSIDL_DESKTOP, None, 0)
    'C:\\Users\\username\\Desktop'

    >>> shell.SHGetFolderPath(0, shellcon.CSIDL_APPDATA, None, 0)
    'C:\\Users\\username\\AppData\\Roaming'

    >>> shell.SHGetFolderPath(0, shellcon.CSIDL_COMMON_APPDATA, None, 0)
    'C:\\ProgramData'

    >>> shell.SHGetFolderPath(0, shellcon.CSIDL_LOCAL_APPDATA, None, 0)
    'C:\\Users\\username\\AppData\\Local'

So it looks to be like the expected windows defaults would be to map

   HOME ->  CSIDL_PROFILE
   Desktop -> CSIDL_DESKTOP
   Start Menu -> CSIDL_PROGRAMS

HOME looks tricky -- may that should be CSIDL_LOCAL_APPDATA or CSIDL_APPDATA, but we do not actually write files to HOME, only to DESKTOP and Start Menu.

Does that look reasonable to you?

**Comment by maphew** [comment]
Microsoft recommends against writing to PROFILE (HOME) and to use one of the APPDATA's instead. My personal preference is to ignore that because I try to keep paths short as reasonable. However I agree that in the context of pyshortcuts it probably doesn't matter.

**Comment by newville** [comment]
@maphew  I completely agree with you on using PROFILE as HOME instead of the icky APPDATA variants!  
I am definitely OK with putting small config files in PROFILE in analogy to HOME on Unices.

**Comment by maphew** [comment]
I managed to get the GUID approach working using dotted syntax, so `folders.Desktop`, `folders.Programs`, etc., in https://github.com/maphew/pyshortcuts/tree/knownfolders. See `win_kf_demo.py`.

I'm not happy with what things are called, 'folders' and 'table' are ambiguous, but imagination/clarity   are not my muses today ;-)

It's probably okay to leave this on the back burner until if/when a real problem with CSIDL shows up. The limitations are things I've only read about and I don't know how big a deal they really are.

**Comment by newville** [comment]
@maphew  OK, thanks.   That looks complete but a little complicated (and: are there really special folders for skydiving?).  Since we need `win32com` to create the Shortcuts, would you agree that

      from win32com.shell  import shell, shellcon
      homedir = shell.SHGetFolderPath(0, shellcon.CSIDL_PROFILE, None, 0)
      desktop = shell.SHGetFolderPath(0, shellcon.CSIDL_DESKTOP, None, 0)
      startmenu = shell.SHGetFolderPath(0, shellcon.CSIDL_PROGRAMS, None, 0)

is simpler and clearer, and more likely to still be understandable and correct in the future?

**Comment by maphew** [comment]
Simpler, clearer and more understandable: yes, let's use it.

Correct in future, or even now? Not sure. The whole reason I went traipsing down the GUID path was because a) I read of problems with unicode and/or people with different launguage locales and b) MSN says CSIDL is deprecated in favour of Known Folders (GUID). However now that I've seen the guts of it I'm content to wait until it actually proves to be a problem. Maybe by that time win32com or equivalent will have a baked in version (and if they don't we do have a lifeboat).

**Comment by newville** [comment]
@maphew Ah, I did not read closely enough to see that the CSIDL_* are deprecated.   Perhaps those should be (https://docs.microsoft.com/en-us/windows/win32/shell/knownfolderid):

    FOLDERID_Profile 
    FOLDERID_Desktop
    FOLDERID_Programs

I'm not at a Windows machine to check this right now but will look into it tomorrow.  I'd like to get this pushed out to PyPI by the weekend....

**Pull request merged**
