### PR TITLE
fix: object of type 'WindowsPath' has no len() 

### PR DESCRIPTION
**Pull request by HaujetZhao**

### CODE REVIEW

**Comment by newville** [comment]
@HaujetZhao Please provide an example code that demonstrates a problem.

**Comment by HaujetZhao** [comment]
```
pip install feeluown
python -m feeluown genicon
```

last time I ran it, encountered this problem.

**Comment by newville** [comment]
@HaujetZhao  I don't have any idea what that library does to create a shortcut.  Please provide python code that demonstrates a problem.    
The current code expects  `icon` to be a string that is the full path to the icon file (and that string has a length) and then we use `os.path` methods on that string.  If someone is passing in a `pathlib.Path` (is that what this library is doing?), that has an `exists()` method, but apparently not a `len()` method (which, honestly, seems like a problem with `pathlib` to me). 

So perhaps the better approach is to explicitly allow for `pathlib.Path` objects.  Well, maybe using `str()` is exactly the right thing to do, but I'm not 100% that it is....

**Comment by HaujetZhao** [comment]
I didn't use your library, it's just I met this error while install feeluown, and I heppened to know the pathlib well, and after adding the str() solved the problem. Using a str() can turn a pathlib.Path object to a string path, and has no harm to other type of path object.

**Comment by newville** [comment]
@HaujetZhao OK, it would be helpful to know exactly what that library used,  and it's sort of odd that no one from that library devel team noticed the problem.  But I guess it is reasonable to expect that `pathlib.Path`s might be sent.

**Comment by newville** [comment]
@HaujetZhao OK, I'll merge this -- even though it doesn't seem incomplete.  Thanks - I may make more changes along this line at some point....

**Pull request merged**
